<a href="https://colab.research.google.com/github/katya-stanzy/python_work/blob/main/DiscreteORContinuous.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('https://raw.githubusercontent.com/a-forty-two/cylons/master/data.csv', header=0)
data.tail(4)

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
565  926682         M  ...                  0.06637          NaN
566  926954         M  ...                  0.07820          NaN
567  927241         M  ...                  0.12400          NaN
568   92751         B  ...                  0.07039          NaN

[4 rows x 33 columns]

In [ ]:
# loop through all the columns and calculate the UNIQUE values inside
# if there are too many unique values-> CONTINUOUS
# if there are too few unique values-> DISCRETE

In [ ]:
# Age 18 20 12 18 17 16 92 67 55 45 45 18 24 
# Address ABC. BCD DEF ABC BCD BCD AED APO 
# Money $1million $1.5million $30 $15 $0 NULL NULL
# Pets 0 0 0 1 2 5 0 0 0
# DISCRETE= ? Address, Pets
# CONTINUOUS= ? Age, Money

In [2]:
# PRINT all unique values!
# if unique values are less-> discrete feature or label
# if unique values are too much-> continuous feature or label

#if its a label-> DISCRETE -> CLASSIFICATION, CONT.-> Regression!
for col_name in data.columns:
  unique_values = data[col_name].value_counts()#unique_value_counter
  unique_values_counted = unique_values.count()
  print(col_name + ' : ' + str(unique_values_counted) )

id : 569
diagnosis : 2
radius_mean : 456
texture_mean : 479
perimeter_mean : 522
area_mean : 539
smoothness_mean : 474
compactness_mean : 537
concavity_mean : 537
concave points_mean : 542
symmetry_mean : 432
fractal_dimension_mean : 499
radius_se : 540
texture_se : 519
perimeter_se : 533
area_se : 528
smoothness_se : 547
compactness_se : 541
concavity_se : 533
concave points_se : 507
symmetry_se : 498
fractal_dimension_se : 545
radius_worst : 457
texture_worst : 511
perimeter_worst : 514
area_worst : 544
smoothness_worst : 411
compactness_worst : 529
concavity_worst : 539
concave points_worst : 492
symmetry_worst : 500
fractal_dimension_worst : 535
Unnamed: 32 : 0